#!/bin/bash

export REAL_HOME="$HOME"
export HOME="$GASH_HOME"

export HISTFILE="$GASH_DATA/history"
export HISTCONTROL="ignoredups"
export HISTIGNORE=""
export HISTSIZE=50000
export HISTFILESIZE=50000


# get this game's configuration
[ -f "$GASH_CONFIG"/config.sh ] && source "$GASH_CONFIG"/config.sh


# shellcheck source=./lib/gameshell.sh
source "$GASH_LIB/gameshell.sh"


export PS1='[mission $(_get_current_mission)] $ '
export PS2="> "
export PS3=""
export PS4="+ "

su() {
    echo "gash: su: command not found" >&2
}

sudo() {
    echo "gash: sudo: command not found" >&2
}

doas() {
    echo "gash: doas: command not found" >&2
}

shopt -s nullglob
for file in "$GASH_CONFIG"/*.bashrc.sh
do
    # shellcheck source=/dev/null
    export MISSION_DIR=$(basename "$file")
    MISSION_DIR=${MISSION_DIR%.bashrc.sh}
    mission_source "$file"
done
shopt -u nullglob

shopt -s nullglob
for file in "$GASH_CONFIG"/*.treasure.sh
do
    # shellcheck source=/dev/null
    export MISSION_DIR=$(basename "$file")
    MISSION_DIR=${MISSION_DIR%.treasure.sh}
    mission_source "$file"
done
shopt -u nullglob

unset file MISSION_DIR

[ "$GASH_MODE" != "DEBUG" ] && ! [ -d "$GASH_BASE/.git" ] && _gash_protect

# save STDIN
export GASH_STDIN=$(realpath /dev/stdin)

_gash_start
