#!/bin/bash

export REAL_HOME="$HOME"
export HOME="$GASH_HOME"

export HISTFILE="$GASH_DATA/history"
export HISTCONTROL="ignoredups"
export HISTIGNORE=""
export HISTSIZE=50000
export HISTFILESIZE=50000

export PATH=$PATH:$GASH_BASE/bin:$GASH_BIN:$GASH_LOCAL_BIN

# shellcheck source=./lib/gameshell.sh
source "$GASH_LIB/gameshell.sh"


export PS1='[mission $(_get_current_mission)] $ '
export PS2="> "
export PS3=""
export PS4="+ "

su() {
    echo "gash: su: command not found" >&2
}

sudo() {
    echo "gash: sudo: command not found" >&2
}

doas() {
    echo "gash: doas: command not found" >&2
}

for f in "$GASH_CONFIG"/*.sh
do
    # shellcheck source=/dev/null
    [ -f "$f" ] && source "$f"
done
unset f

_gash_start
