#!/bin/bash

export REAL_HOME="$HOME"
export HOME="$GSH_HOME"

export HISTFILE="$GSH_CONFIG/history"
export HISTCONTROL="ignoredups"
export HISTIGNORE=""
export HISTSIZE=50000
export HISTFILESIZE=50000

unset LS_COLORS
unset EDITOR

# get this game's configuration
[ -f "$GSH_CONFIG"/config.sh ] && . "$GSH_CONFIG"/config.sh

export PATH=$GSH_ROOT/bin:$PATH:$GSH_BIN
# export PATH=$PATH:$GSH_ROOT/bin:$GSH_BIN

# shellcheck source=./lib/gameshell.sh
. "$GSH_LIB/gsh.sh"

# completion for (some) gsh commands
complete -W 'check exit goal help index log reset stat welcome' gsh

export PS1='[mission $(gsh pcm)] $ '
export PS2="> "
export PS3=""
export PS4="+ "

# running bash should take you "out" of GameShell
alias bash='bash --rcfile "$GSH_LIB/gshrc" -i'

# try to prevent using sudo and similar
su() {
    echo "gsh: su: command not found" >&2
}

sudo() {
    echo "gsh: sudo: command not found" >&2
}

doas() {
    echo "gsh: doas: command not found" >&2
}

# remove quotes from filenames with special characters
# NOTE: --literal doesn't exist in freebsd
if ls --literal / &> /dev/null
then
    alias ls="ls --literal"
fi


shopt -s nullglob
for file in "$GSH_CONFIG"/gshrc_*.sh
do
    # shellcheck source=/dev/null
    . "$file"
done
shopt -u nullglob

shopt -s nullglob
for file in "$GSH_CONFIG"/treasure_*.sh
do
    # shellcheck source=/dev/null
    . "$file"
done
shopt -u nullglob

unset file MISSION_DIR

[ "$GSH_MODE" != "DEBUG" ] && ! [ -d "$GSH_ROOT/.git" ] && _gsh_protect

__gsh_start
