#!/bin/sh

. gsh_gettext.sh

VERSION='developpment version (1653583082)'

echo "Gameshell $VERSION"

echo

echo $(gettext "The latest version of Gameshell is available at")
echo "    https://github.com/phyver/GameShell"
