name: GameShell CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the GameShell repo
        uses: actions/checkout@v2
      # - if: ${{ matrix.platform == 'ubuntu-latest' }}
      #   name: Install Linux deps
      #   run: |
      #     sudo apt install gettext python3 man-db psmisc nano tree bsdmainutils
      # - if: ${{ matrix.platform == 'macos-latest' }}
      #   name: Install macOS deps
      #   run: |
      #     brew install coreutils pstree tree man-db
      - name: Run the tests
        run: |
            echo ps; ps || true
            echo ps -c; ps -c || true
            echo ps -ce; ps -ce || true
            echo ps -ceo pid,comm,ppid; ps -ceo pid,comm,ppid || true
            echo ps -o pid,comm,ppid; ps -o pid,comm,ppid || true
